language: csharp
mono: none
dist: xenial
os: linux
addons:
  snaps:
    - name: dotnet-sdk
      confinement: classic
      channel: 5.0/stable
install:
  - 'export PATH="$PATH:/home/travis/.dotnet/tools"'
  - 'export PATH="$PATH:$HOME/.local/bin"'
  - pip install --user awscli
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
jobs:
  include:
    - stage: test_unit_testing
      name: Run tests on SharesightImporter
      script:
        - dotnet restore
        - dotnet build
        - dotnet test test/SharesightImporter.Tests -v m